---
title: Dabsh Mori
timezone: UTC
collections:
  featured_categories:
    title: Featured Categories
    output: true
    permalink: "/:name/"
  featured_tags:
    title: Featured Tags
    output: true
    permalink: "/tag-:name/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: assets/**
  values:
    sitemap: false
- scope:
    path: licenses/**
  values:
    layout: plain
    sitemap: false
- scope:
    path: google93abcae935f31b7d.html
  values:
    sitemap: false
- scope:
    path: navera03014a241218f942080c56d67e79469.html
  values:
    sitemap: false
- scope:
    path: ''
    type: posts
  values:
    comments: true
    applause_button: true
- scope:
    path: ''
    type: projects
  values:
    seo:
      type: WebPage
- scope:
    path: ''
    type: featured_categories
  values:
    seo:
      type: WebPage
- scope:
    path: ''
    type: featured_tags
  values:
    seo:
      type: WebPage
url: https://MoriXplus.github.io
baseurl: ''
lang: fa-IR, en-US
description: 'I share my thought maybe that can help you .

'
tagline: 'My thought.

'
keywords:
- morteza mehrdad programmer devlog godot flutter android studio java C#
logo: "/assets/img/seattle.png"
author:
  name: Morteza Mehrdad
  email: morixplus@gmail.com
  picture: "/assets/img/seattle.png"
  social:
    github: morixplus
    email: morixplus@gmail.com
copyright: "© 2022. All rights reserved."
permalink: none
paginate: 10
paginate_path: "/page-:num/"
excerpt_separator: "<!--more-->"
accent_image: "/assets/img/sidebar-bg.jpg"
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)
google_fonts: Noto+Sans+KR|JetBrains+Mono|Nanum+Gothic+Coding
font: Noto Sans KR, Helvetica, Arial, sans-serif
font_heading: Helvetica, Arial, sans-serif
font_code: JetBrains Mono, Nanum Gothic Coding, Menlo, Monaco, Consolas, monospace;
kramdown:
  math_engine: mathjax
  math_engine_opts: {}
  footnote_backlink: "&#x21a9;&#xfe0e;"
comments:
  provider: giscus
giscus:
  repo: MoriXplus/MoriXplus.github.io
  repo-id: MDEwOlJlcG9zaXRvcnkyNzU4Mjk1NTc=
  category: Comments
  category-id: DIC_kwDOEHDTNc4B-MIg
  mapping: pathname
  reaction-enabled: '1'
  data-emit-metadata: '0'
  theme: dark_dimmed
  data-lang: en
  crossorigin: anonymous
hydejack:
  post_addons:
  - about
  - comments
  project_addons:
  - about
  - other
  - comments
  no_mark_external: true
  no_push_state: false
  no_drawer: false
  no_navbar: false
  no_search: false
  no_inline_css: false
  no_page_style: true
  no_break_layout: true
  no_toc: false
  no_third_column: false
  no_large_headings: true
  no_structured_data: false
  no_theme_color: false
  no_breadcrumbs: false
  use_lsi: false
  cookies_banner: true
  advertise: false
  clap_button: false
  hide_dates: false
  hide_last_modified: false
  dark_mode:
    always: true
    dynamic: true
    icon: false
  offline:
    enabled: false
    cache_version: 13
    precache_assets:
    - "/assets/img/swipe.svg"
exclude:
- ".jekyll-cache"
- ".sass-cache"
- "*.toml"
- vendor
- Gemfile
- Gemfile.lock
- node_modules
include:
- ".well-known"
- LICENSE.md
plugins:
- jekyll-default-layout
- jekyll-feed
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-titles-from-headings
- jekyll-include-cache
- jekyll-last-modified-at
- jemoji
optional_front_matter:
  remove_originals: true
readme_index:
  remove_originals: true
  with_frontmatter: true
relative_links:
  collections: true
titles_from_headings:
  strip_title: true
  collections: true
compress_html:
  comments:
  - "<!-- "
  - " -->"
  clippings: all
  endings: all
  ignore:
    envs:
    - development
sass:
  style: compressed
jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      description: 'A short ~160 character description of your post for search engines,
        social media previews, etc.

'
      image:
        path: "/assets/img/sidebar-bg.jpg"
    posts:
      layout: post
      description: 'A short ~160 character description of your post for search engines,
        social media previews, etc.

'
      image:
        path: "/assets/img/sidebar-bg.jpg"
    projects:
      layout: project
      description: 'A short ~160 character description of your post for search engines,
        social media previews, etc.

'
      image:
        path: "/assets/img/sidebar-bg.jpg"
      links:
      - title: Project Link
        url: https://example.com
feed:
  categories:
  - devlog
  - review
